class AppStorage{

    storeToken(token){
        localStorage.setItem('token',token);
    }
    storeName(name){
        localStorage.setItem('name',name);
    }
    storeEmail(email){
        localStorage.setItem('email',email);
    }
    storeUserType(userType){
        localStorage.setItem('user_type',userType);
    }
    storeVillageId(villageId){
        localStorage.setItem('villageId',villageId);
    }
    store(data){
        this.storeToken(data.access_token)
        this.storeName(data.name)
        this.storeEmail(data.email)
        this.storeUserType(data.user_type)
        this.storeVillageId(data.village_id)
    }
    clear(){
        localStorage.removeItem('token')
        localStorage.removeItem('name')
        localStorage.removeItem('email')
        localStorage.removeItem('user_type')
        localStorage.removeItem('villageId')
    }
    getToken(){
        localStorage.getItem(token);
    }
    getName(){
        localStorage.getItem(name);
    }
    getEmail(){
        localStorage.getItem(email);
    }
    getUserType(){
        localStorage.getItem(user_type);
    }
    getVillageId(){
        localStorage.getItem(villageId);
    }
}
export default AppStorage = new AppStorage();